### ISSUE TITLE
Please update Runtime org.kde.Platform to 5.15-23.08

### ISSUE THREAD

**Issue by oniGino** [flathub/org.libretro.RetroArch#260]
5.15-22.08 is pretty old at this point

please bump to 5.15-23.08  it has been out for some time.

Also wouldn't be surprised if this helps with 

#106 as well

**Comment by AceMasterX27** [comment]
Hi, i have an issue right now related to this. My system mesa drivers updated to 23.3.0 , and after that I couldn't open various flatpak apps that use libgl. Then there was a new update for the org.freedesktop.Platform 23.08.7, which includes mesa 23.3.0, and that fixed the issues with all the affected flatpak apps except Retroarch. Someone told me that it may because Retroarch uses an older runtime.
I placed info about the issue here: https://discourse.flathub.org/t/problems-with-mesa-drivers/5574

**Comment by RobLoach** [comment]
Thanks for jumping in. I made a pull request, but it seems to be failing with GameMode. Know what's wrong with it? https://github.com/flathub/org.libretro.RetroArch/pull/261

**Comment by RobLoach** [comment]
:rocket:
