### ISSUE TITLE
Investigate updating to 18.08 runtime

### ISSUE THREAD

**Issue by TingPing** [flathub/org.libretro.RetroArch#66]
A new freedesktop runtime was released and its a good idea to move to it. Will just require some testing to ensure everything is working.

**Comment by RobLoach** [comment]
Need the Qt toolkit for WIMP. It comes out of the box with KDE: https://github.com/flathub/org.libretro.RetroArch/pull/71

What do you think? Freedesktop and compile in Qt, or just roll with KDE?

**Comment by TingPing** [comment]
KDE runtime is big, but they will do a better job maintaining it than an app would.

Personally I think the WIMP is really bad and doesn't provide much value to users.. but what do I know.

**Comment by RobLoach** [comment]
Could try building it as an individual module. Would really love to keep using the freedesktop one due to KDE bloat.

Looks like there's a [shared flathub qt5 module](https://github.com/flathub/shared-modules/tree/master/qt4), but I think WIMP needs Qt5.

> Personally I think the WIMP is really bad and doesn't provide much value to users.. but what do I know.

It is young. I don't use it either, but others may find value out of it. Been requested, worth investigating its compilation.... I'll keep it out of this 1.7.4 release cycle. Perhaps consider getting Qt5 in there sometime in the next weeks.
